<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook__ctools_plugin_api().
 */
function islandora_context_ctools_plugin_api($module, $api) {
  if ($module == 'context' && $api == 'plugins') {
    return array('version' => 3);
  }
}

/**
 * Implements hook_context_plugins().
 */
function islandora_context_context_plugins() {
  $plugins = array();
  $plugins['islandora_context_condition_namespace'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'islandora_context') . '/plugins',
      'file' => 'islandora_context_condition_namespace.inc',
      'class' => 'IslandoraContextConditionNamespace',
      'parent' => 'context_condition',
    ),
  );
  return $plugins;
}

/**
 * Implements hook_context_registry().
 */
function islandora_context_context_registry() {
  return array(
    'conditions' => array(
      'islandora_context_condition_namespace' => array(
        'title' => t('Islandora PID Namespace'),
        'description' => t("Choose this condition if you want to detect an object's PID namespace."),
        'plugin' => 'islandora_context_condition_namespace',
      ),
    ),
  );
}

/**
 * Implements hook_islandora_view_object().
 */
function islandora_context_islandora_view_object(AbstractObject $object) {
  if ($plugin = context_get_plugin('condition', 'islandora_context_condition_namespace')) {
    $plugin->execute($object);
  }
  return array();
}
